const ShopActionTypes = {
  FETCH_COLLECTIONS_START: "FETCH_COLLETIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLETIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE:  "FETCH_COLLECTIONS_FAILURE"
};

export default ShopActionTypes;
